language: node_js
node_js:
  - "7"
services:
  - postgresql
before_script:
  - psql -c "create database travis;" -U postgres
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g sequelize-cli
script:
  - npm test
after_script:
  - npm run coverage
after_success: npm run coverage
